workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - cd apk-main
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - apk-main/build/app/outputs/flutter-apk/app-release.apk
